enclave-cc: fix HW kustomization
The 'images' key was missing and resulted in

error: invalid Kustomization: yaml: line 8: did not find expected key

Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>