tests/e2e: Update requests package
- Due to a bug in requests 2.29.0 we need to downgrade it
to avoid the error:
`Error while fetching server API version: request() got an
unexpected keyword argument 'chunked'`
- See https://github.com/docker/docker-py/issues/3113

Fixes: #206
Signed-off-by: stevenhorsman <steven@uk.ibm.com>